# Generated by Django 3.2.6 on 2021-09-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='title')),
                ('year', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='year')),
                ('url', models.URLField(default='', verbose_name='url')),
            ],
            options={
                'verbose_name': 'conference',
                'verbose_name_plural': 'conferences',
            },
        ),
    ]
