# Generated by Django 3.2.6 on 2021-09-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
        ('anthology', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='papers',
            field=models.ManyToManyField(to='papers.Paper'),
        ),
    ]
