# Generated by Django 3.2.6 on 2021-09-03 18:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50, verbose_name='title')),
                ('year', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='year')),
                ('url', models.URLField(default='', verbose_name='url')),
                ('authors', models.CharField(default='', max_length=200, verbose_name='authors')),
                ('abstract', models.TextField(default='', verbose_name='abstract')),
                ('reader_desc', models.TextField(default='', verbose_name='notes')),
            ],
            options={
                'verbose_name': 'paper',
                'verbose_name_plural': 'papers',
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='name')),
                ('url', models.URLField(default='', verbose_name='url')),
                ('info', models.TextField(default='', verbose_name='info')),
                ('papers', models.ManyToManyField(to='papers.Paper')),
            ],
            options={
                'verbose_name': 'author',
                'verbose_name_plural': 'authors',
            },
        ),
    ]
