# Generated by Django 3.2.6 on 2021-09-09 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='conf',
            field=models.CharField(default='', max_length=50, verbose_name='conf'),
        ),
        migrations.AddField(
            model_name='paper',
            name='conf_content',
            field=models.CharField(default='', max_length=50, verbose_name='conf_content'),
        ),
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='title')),
                ('year', models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(4)], verbose_name='year')),
                ('url', models.URLField(default='', verbose_name='url')),
                ('papers', models.ManyToManyField(to='papers.Paper')),
            ],
            options={
                'verbose_name': 'conference',
                'verbose_name_plural': 'conferences',
            },
        ),
    ]
